#!/usr/bin/env ruby

site 'http://community.opscode.com/api/v1'

# System
cookbook 'ubuntu'
cookbook 'apt', '>= 1.4.8'

cookbook 'user', git: 'git://github.com/burriko/chef-user.git', ref: '055c009bfca500c2b10355764063de8a7e7174a9'
#:git => 'git://github.com/fnichol/chef-user.git', :ref => 'v0.3.0'
cookbook 'sudo', '>= 1.1.0'
cookbook 'cron', '>= 1.0.4'
cookbook 'curl', '>= 1.1.0'
cookbook 'vim'

cookbook 'hostname'
cookbook 'sysstat', '>= 1.1.8'
cookbook 'timezone', '>= 0.0.1'
cookbook 'ntp', '>= 1.1.8'
cookbook 'openssh', '>= 0.8.0'
cookbook 'openssl', '>= 1.0.0'

cookbook 'iptables', '>= 0.10.0'

cookbook 'logrotate', '>= 0.8.2'

cookbook 'git'
cookbook 'build-essential'
cookbook 'imagemagick', '>= 0.2.2'
cookbook 'xml'
cookbook 'zlib'

cookbook 'pkgin'
cookbook 'aws'

# SmartOS
cookbook 'smartos', :git => 'git://github.com/modcloth-cookbooks/smartos.git'
cookbook 'smf', :git => 'git://github.com/modcloth-cookbooks/smf.git'
cookbook 'java', :path => '../java' #:git => 'git://github.com/wanelo-chef/java.git'
cookbook 'jetty', :github => 'ToQoz/chef-jetty' #:git => 'git://github.com/theozaurus/chef-jetty.git'

# Web Application
cookbook 'nginx'
cookbook 'unicorn'
cookbook 'ssl', '>= 1.0.7'
cookbook 'mysql'
cookbook 'database', git: 'git://github.com/michaelklapper/database.git',
  ref: 'grant_statement'

cookbook 'fanfare', git: 'git://github.com/Lanio/chef-fanfare.git'
cookbook 'company', path: '../company-cookbook'

# Development
cookbook 'tmux'
cookbook 'ssh', :git => 'git://github.com/markolson/chef-ssh.git'
cookbook 'ssh-keys', :git => 'git://github.com/dkastner/chef-ssh-keys.git'

# ruby

cookbook 'rbenv', git: 'git://github.com/fnichol/chef-rbenv.git', :ref => 'v0.7.2'
cookbook 'ruby_build', git: 'git://github.com/fnichol/chef-ruby_build.git', :ref => 'v0.7.2'

cookbook 'monit'

cookbook 'apache2'
cookbook 'passenger_apache2'

cookbook 'solr', github: 'dkastner/chef-solr'
#cookbook 'maven'
#cookbook 'solr-jetty-maven', path: '../chef-solr-jetty-maven' # git: 'git://github.com/dkastner/chef-solr'
cookbook 'redis', git: 'git://github.com/wanelo-chef/redis.git'
cookbook 'redisio'

cookbook 'collectd', git: 'git://github.com/dkastner/chef-collectd'
cookbook 'graphite', git: 'git://github.com/hw-cookbooks/graphite.git'
cookbook 'statsd',   git: 'git://github.com/hectcastro/chef-statsd.git'
cookbook 'graphiti', git: 'git://github.com/dkastner/chef-graphiti.git'

cookbook 'golang', github: 'NOX73/chef-golang'
cookbook 'docker', github: 'bflad/chef-docker'
